create table COUPON (
    ID INTEGER GENERATED ALWAYS AS IDENTITY,
    WEBSITE VARCHAR(100) NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    DISCOUNT INTEGER NOT NULL,
    DISCOUNT_TYPE ENUM('percentage', 'dollars') NOT NULL,
    STATUS ENUM('reviewing', 'published') NOT NULL,
    DESCRIPTION VARCHAR(200)
);